assembly=
threads=
outdir=
depth=
# ^^^ this is the depth file generated by the jgi summarize command
minimum_contig_size=
seed=
# ^^^ you don't necessarily need this. Any number is fine, I pick my favorite normally. 

#run it 
metabat2 --seed $seed -v -d --numThreads $threads --minCVSum 0 --minCV 0.1 --minContig $minimum_contigs_size -i $assembly -a $depth -o $outdir
